#!/bin/bash
# This script executes a chain of commands
# on all the member servers, in parallel.
# Commands are defined in .sh files (see
# docmd.sh); all failed executions are
# put to the FAILURES file
rm -f FAILURES
rm -rf logs
mkdir logs

if [ -z "$SERVERS" ]; then
    SERVERS="servers.txt"
fi

for srv in `grep -v '^#' $SERVERS`; do
    (
        if ! ./docmd $srv $1; then
            echo $srv >> FAILURES
            echo $srv FAILED
            break
        fi
    ) &
done

wait
echo DONE
