#!/usr/bin/perl -w

$SERVER=shift;
%HOSTS = ();
%CHANN = ( "#0" => "none" );
%EVENTS = ( "#0" => {"+hs"=>0} );

open(SRV,$ENV{"HOME"}."/.ssh/config") or die;
while (<SRV>) {
    $srvname=$1 if /Host (\S+)/;
    $HOSTS{$1}=$srvname if /HostName (\S+)/;
}
close SRV;

while (<>) {
    /([\d\_]+) (#\d+) (\S+) (.*)/ or next;
    my $time = $1;
    my $channel = $2;
    my $event = $3;
    my $rest = $4;
    if ($event eq "sent") {
        $rest =~ /\d+b ([\d\.]+):/;
        $ip = $1;
        $CHANN{"$channel"} = $HOSTS{$ip};
        $EVENTS{"$channel"} = { "+hs"=>0 } if not exists $EVENTS{"$channel"};
    }
    my $host = $CHANN{"$channel"};
    $host = "unknown" if not $host;
    
    print "$time $SERVER $host$channel $event $rest\n";

    # DO STATS
    $EVENTS{"$channel"}{"$event"} = 0 if not exists $EVENTS{"$channel"}{"$event"};
    $EVENTS{"$channel"}{"$event"}++;

}

for $channel (keys %CHANN) {
    my $host = $CHANN{"$channel"};
    open(STATS,"> harvest/$SERVER-$host.stat") or die;
    for $event ( keys %{ $EVENTS{"$channel"} } ) {
        print STATS "$event\t".($EVENTS{"$channel"}{"$event"})."\n";
    }
    close STATS;
}
